# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 180fb1f2d18acfee58afafa70350bd73efccb208b19cf70f015f432e0eda3a896fd92fd602e24a974c85799beb24ea54e8fb00be3972b44a88006432a38b112d

test:
  secret_key_base: c10a8cae13a0e6515a43c91674fef47b663ef88b3ca33c20de09b423f30c8e7a44546ff56e575132858395f49188ae735a6aade0ee767ddc8e23b9d90329ab9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
